apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    app: {{ .Release.Name }}-my-flaskapp
  ports:
      - protocol: TCP
        port: 5000
        targetPort: 5000
  type: LoadBalancer